### ISSUE TITLE
Connecting to a Wireless Network turns off GSM

### ISSUE THREAD

**Issue by geohuk** [crdroidandroid/android_device_htc_m8d#1]
Hey I've got the latest crDroid and opengapps as of today. No mods or anything like that.

Initially after reboot everything works fine. But immediately after disconnecting and connecting to a wireless network GSM is disabled. I can make and receive no calls and there is no data connection of course.

Cheers,
Georgi

**Comment by firebird11** [comment]
This is a lineage matter, it will be solved soon

**Comment by geohuk** [comment]
Yeah, I managed to fix it by switching to permissive SELinux.
